import { env } from "../../config/env.js";
import { logger } from "../../utils/logger.js";

export class PdfService {
  /**
   * Generates a PDF buffer for a given assignment ID by rendering the frontend output page in a headless browser.
   * @param assignmentId The ID of the assignment to print
   */
  async generateAssignmentPdf(assignmentId: string): Promise<Buffer> {
    const url = `${env.CLIENT_ORIGIN}/output?id=${assignmentId}`;
    logger.info({ url, assignmentId }, "Launching Puppeteer to generate PDF");

    const puppeteer = (await import("puppeteer")).default;
    const browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--font-render-hinting=none",
      ],
    });

    try {
      const page = await browser.newPage();

      // Configure a realistic viewport
      await page.setViewport({
        width: 1200,
        height: 1600,
        deviceScaleFactor: 1,
      });

      // Navigate to the output page and wait until network is completely idle
      await page.goto(url, {
        waitUntil: "networkidle0",
        timeout: 30000,
      });

      // Wait for fonts to be fully loaded and ready
      await page.evaluate("document.fonts.ready");

      // Wait for React hydration and dynamic questions to load completely
      // Checking for the presence of the question-card ensures full data rendering
      await page.waitForSelector(".question-card", {
        timeout: 15000,
      });

      // Inject a brief extra pause to allow all React state updates to render and settle
      await new Promise((resolve) => setTimeout(resolve, 500));

      logger.debug({ assignmentId }, "Generating PDF from Puppeteer page");

      // Generate the PDF matching strict school paper requirements
      const pdfBuffer = await page.pdf({
        format: "A4",
        printBackground: true,
        displayHeaderFooter: true,
        headerTemplate: `<div style="font-size: 0px; height: 0px;"></div>`,
        footerTemplate: `
          <div style="width: 100%; font-size: 9px; font-family: system-ui, -apple-system, sans-serif; color: #5e5e5e; display: flex; justify-content: space-between; padding: 0 15mm; box-sizing: border-box;">
            <div style="flex: 1; text-align: left;"></div>
            <div style="flex: 1; text-align: center; color: #303030;">Page <span class="pageNumber"></span></div>
            <div style="flex: 1; text-align: right; color: #5e5e5e;">Generated by Vedam AI</div>
          </div>
        `,
        margin: {
          top: "15mm",
          bottom: "18mm",
          left: "15mm",
          right: "15mm",
        },
        preferCSSPageSize: false,
      });

      logger.info({ assignmentId }, "PDF generated successfully");
      return Buffer.from(pdfBuffer);
    } catch (error) {
      logger.error({ err: error, assignmentId }, "Error during PDF generation in Puppeteer");
      throw error;
    } finally {
      await browser.close();
      logger.debug({ assignmentId }, "Puppeteer browser closed");
    }
  }
}

export const pdfService = new PdfService();
